In [1]:
#importar as bibliotecas 
from numpy import pi
from numpy import sys
import numpy as np

In [2]:
print('Versão atual do numpy', np.__version__)

Versão atual do numpy 1.18.5


In [6]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [7]:
a[2]

8

In [8]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [13]:
#Equivalente a [0:6:2]=1000
#do inicio para a posição 6
#Definir do primeiro indo a cada dois elementos para 1000
a[:6:2]=1000
a

array([1000,    1, 1000,   27, 1000,  125, 1000,  343,  512,  729],
      dtype=int32)

In [15]:
#Inverter a
a[::-1]

array([ 729,  512,  343, 1000,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [17]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
9.999999999999998
6.999999999999999
7.999999999999999
8.999999999999998


In [19]:
#Criando função 
def f(x, y):
    return 10 * x+y

b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [20]:
b[2,3]

23

In [23]:
#Cada linha na segunda coluna de b
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [27]:
#Equivalente a anterior
b[: , 1]

array([ 1, 11, 21, 31, 41])